# Generated by Django 4.2.7 on 2026-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_vehichle_number_courier_vehicle_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courier',
            name='logistics_c_is_acti_279a5f_idx',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='is_active',
        ),
        migrations.AddField(
            model_name='courier',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Automatically set to False when assigned to an active order, and back to True when the order is completed or cancelled.'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='current_lat',
            field=models.FloatField(default=30.050180997609587, help_text='Current latitude — defaults to Cairo if not provided'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='current_lng',
            field=models.FloatField(default=31.232585906982425, help_text='Current longitude — defaults to Cairo if not provided'),
        ),
        migrations.AlterField(
            model_name='livetracking',
            name='distance_to_destination',
            field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AddIndex(
            model_name='courier',
            index=models.Index(fields=['is_available'], name='logistics_c_is_avai_d733e1_idx'),
        ),
    ]
